language: python

sudo: false

python:
  - 3.5
  - 3.6

env:
  global:
    - PIP_DEPS="jsonschema traitlets jinja2 pytest pytest-cov"

before_install:
- pip install pip --upgrade
- pip install $PIP_DEPS

install:
- python setup.py install

script:
- mkdir for_test
- cd for_test
- py.test --pyargs altair_parser --doctest-module --cov-report term-missing --cov=altair_parser

