language: python
cache: pip
sudo: false

  
# Enable 3.7 without globally enabling sudo and xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    - PIP_DEPS="jsonschema pytest pytest-cov"

before_install:
- pip install pip --upgrade
- pip install $PIP_DEPS

install:
- python setup.py install

script:
- mkdir for_test
- cd for_test;
- py.test --pyargs schemapi --doctest-module --cov-report term-missing --cov=schemapi;
