sudo: false

env:
  global:
    - CONDA_DEPS="jsonschema traitlets jinja2 pytest pytest-cov"

matrix:
  include:
    - os: osx
      env:
         - PYTHON_VERSION=3.6
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
    - os: linux
      env:
         - PYTHON_VERSION=3.6
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"


before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda config --add channels conda-forge
- conda install python=$PYTHON_VERSION $CONDA_DEPS

install:
- python setup.py install

script:
- mkdir for_test
- cd for_test
- py.test --pyargs altair_parser --doctest-module --cov-report term-missing --cov=altair_parser

